

const Devices = () => {
  return (
    <div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
      <div>device</div>
    </div>
  )
}

export default Devices